"""Add hashed_password to User and user_id to Server

Revision ID: 6f2a46c24a4e
Revises: 74fafda73355
Create Date: 2025-05-06 22:23:01.948125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2a46c24a4e'
down_revision: Union[str, None] = '74fafda73355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'servers', 'users', ['user_id'], ['user_id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_column('servers', 'user_id')
    # ### end Alembic commands ###
