"""Added created_at to Server model

Revision ID: 74fafda73355
Revises: 2a852455fb77
Create Date: 2025-03-14 03:23:57.274118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fafda73355'
down_revision: Union[str, None] = '2a852455fb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('server_id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_foreign_key(None, 'alert_rules', 'servers', ['server_id'], ['server_id'])
    op.create_foreign_key(None, 'alerts', 'servers', ['server_id'], ['server_id'])
    op.create_foreign_key(None, 'metrics', 'servers', ['server_id'], ['server_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alert_rules', type_='foreignkey')
    op.drop_table('servers')
    # ### end Alembic commands ###
